### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by kennyparsons** [mauriceoegerli/viewtube-vue#1512]
### Describe the Bug
Yarn install fails after 13 minutes, with nearly every package failing due to memory errors. 

### Steps to Reproduce the Bug

1. `yarn install`
2. Check output
3.

### Device Info 
server: debian 10, non docker install

### Additional Context
```
jiru443@atlas:~/.userdata/viewtube-vue$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @nuxt/types@npm:2.15.8 doesn't provide webpack (p1a032), requested by sass-loader
➤ YN0002: │ @nuxtjs/composition-api@npm:0.32.0 [65614] doesn't provide @vue/runtime-dom (p65388), requested by unplugin-vue2-script-setup
➤ YN0002: │ @nuxtjs/eslint-config@npm:6.0.1 [19daa] doesn't provide typescript (p393f2), requested by eslint-plugin-jest
➤ YN0002: │ client@workspace:client doesn't provide @vue/runtime-dom (pc2595), requested by unplugin-vue2-script-setup
➤ YN0060: │ client@workspace:client provides eslint (p640fa) with version 8.19.0, which doesn't satisfy what @nuxtjs/eslint-config-typescript and some of its descendants request
➤ YN0060: │ client@workspace:client provides webpack (p94394) with version 5.72.0, which doesn't satisfy what @nuxt/typescript-build and some of its descendants request
➤ YN0002: │ eslint-plugin-nuxt@npm:3.2.0 doesn't provide eslint (p5fe95), requested by vue-eslint-parser
➤ YN0002: │ eslint-plugin-nuxt@npm:3.2.0 doesn't provide eslint (pd1ce4), requested by eslint-plugin-vue
➤ YN0002: │ nuxt-typed-vuex@npm:0.3.1 [65614] doesn't provide vuex (p69a0d), requested by typed-vuex
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 358ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0068: │ run-script-webpack-plugin ➤ peerDependencies ➤ webpack: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: ⠸ --------------------------------------------------------------------------------
➤ YN0001: │ RangeError: @ampproject/remapping@npm:2.2.0: WebAssembly.Instance(): Out of memory: wasm memory
    at Sh (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:196:231902)
    at vh (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:196:232663)
    at /home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:198:48232
    at D5 (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:392:17260)
    at fn (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:392:17295)
    at Nt.fetchPackageFromCache (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:429:2947)
    at async Qo.fetch (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:710:24627)
    at async yd.fetch (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:391:437)
    at async /home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:439:10155

... truncated ....

➤ YN0000: ⠼ ===============================================================================-
➤ YN0001: │ RangeError: typescript@patch:typescript@npm%3A4.7.4#~builtin<compat/typescript>::version=4.7.4&hash=f456af: WebAssembly.Instance(): Out of memory: wasm memory
    at Sh (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:196:231902)
    at vh (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:196:232663)
    at /home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:198:48232
    at D5 (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:392:17260)
    at fn (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:392:17295)
    at Nt.fetchPackageFromCache (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:429:2947)
    at async rO.fetch (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:736:883)
    at async yd.fetch (/home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:391:437)
    at async /home10/jiru443/.userdata/viewtube-vue/.yarn/releases/yarn-3.2.2.cjs:439:10155
➤ YN0000: └ Completed in 13m 60s
➤ YN0000: Failed with errors in 14m 1s
```

```bash
jiru443@atlas:~$ npm -v
8.15.1
jiru443@atlas:~$ node -v
v16.14.0
jiru443@atlas:~$ yarn -v
3.2.2
```

**Comment by moisout** [comment]
I have since switched from yarn to pnpm, installation should be a lot smoother now.

**Comment by moisout** [comment]
There is now developer documentation on https://viewtube.wiki/development. Please open a new issue if you run into any issues.
