### ISSUE TITLE
500 Internal Server Error when attempting to watch any subscription video

### ISSUE THREAD

**Issue by MisterDeee** [mauriceoegerli/viewtube-vue#1895]
### Describe the Bug

Click on any video from any subscribed channel (imported via CSV), receive a 500 Internal Server error in the UI.

### Expected Behaviour

Video would play as expected.

### Screenshot/Screen recording

Multiple errors show up in the Docker logs when attempting to view any video:

Premature close
  at new NodeError (node:internal/errors:400:5)
  at onclose (node:internal/streams/end-of-stream:148:30)
  at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Premature close
  at new NodeError (node:internal/errors:400:5)
  at onclose (node:internal/streams/end-of-stream:148:30)
  at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Premature close
  at new NodeError (node:internal/errors:400:5)
  at onclose (node:internal/streams/end-of-stream:148:30)
  at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
 ERROR  Cannot read properties of null (reading 'lastSubscriptionsRefresh')
  at server/dist/main.cjs:5885:33
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async SubscriptionsService.getSubscriptionFeed (server/dist/main.cjs:5884:21)
  at async SubscriptionsController.getSubscriptionVideos (server/dist/main.cjs:7084:20)
 ERROR  Cannot read properties of null (reading 'lastSubscriptionsRefresh')
  at server/dist/main.cjs:5885:33
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async SubscriptionsService.getSubscriptionFeed (server/dist/main.cjs:5884:21)
  at async SubscriptionsController.getSubscriptionVideos (server/dist/main.cjs:7084:20)
WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".

### Device Info

- Server Device: Docker container (Portainer)
- Server OS: Debian 11 (mauriceo/viewtube:latest, mongo:5, redis:7)
- Host Device: Dell XPS 8940 (Core i9-10900K w/ 64GB RAM)
- Host OS: Windows 10 Pro for Workstations
- Browser: Firefox
- Version: 111.0.1 (64-bit)

### Additional Context

Let me know if you need anything else (docker-compose, etc) to help with tracking this down!

**Comment by JamsRepos** [comment]
https://github.com/ViewTube/viewtube/issues/1890
