### ISSUE TITLE
Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by Jogai** [mauriceoegerli/viewtube-vue#2258]
### Describe the Bug

Error on first run after following the docker guide here https://viewtube.wiki/installation/docker

### Steps to Reproduce the Bug

1. Copy docker file as shown
2. run `docker-compose up -d`
3. Visit host

### Expected Behaviour

First screen

### Screenshot/Screen recording

Shows:
> 500 
> Cannot read properties of undefined (reading 'trim')

### Device Info

- Device: Docker version 24.0.5, build ced0996600
- OS: Linux x86_64

### Additional Context

Tried it with latest & dev docker images

The log:

```
2023-09-18 14:53:19
 [ViewTube] Info	9/18/2023, 2:53:19 PM [NestApplication] Nest application successfully started - {}
2023-09-18 14:53:51
 [ViewTube] Error	9/18/2023, 2:53:51 PM [ExceptionsHandler] fetch failed - {"stack":["TypeError: fetch failed\n    at fetch (/home/app/node_modules/.pnpm/undici@5.23.0/node_modules/undici/index.js:109:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]}
2023-09-18 14:53:59
 [ViewTube] Error	9/18/2023, 2:53:59 PM [ExceptionsHandler] fetch failed - {"stack":["TypeError: fetch failed\n    at fetch (/home/app/node_modules/.pnpm/undici@5.23.0/node_modules/undici/index.js:109:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]}
2023-09-18 14:54:01
 [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'trim')
2023-09-18 14:54:01
   at desanitize (./client/.output/server/chunks/app/server.mjs:1243:52)  
2023-09-18 14:54:01
   at ./client/.output/server/chunks/app/server.mjs:1249:31  
2023-09-18 14:54:01
   at Array.reduce ()  
2023-09-18 14:54:01
   at parseCookieString (./client/.output/server/chunks/app/server.mjs:1246:139)  
2023-09-18 14:54:01
   at ./client/.output/server/chunks/app/server.mjs:1488:19  
2023-09-18 14:54:01
   at ./client/.output/server/chunks/app/server.mjs:124:70  
2023-09-18 14:54:01
   at fn (./client/.output/server/chunks/app/server.mjs:158:44)  
2023-09-18 14:54:01
   at Object.callAsync (./client/.output/server/node_modules/unctx/dist/index.mjs:68:55)  
2023-09-18 14:54:01
   at ./client/.output/server/chunks/app/server.mjs:160:56  
2023-09-18 14:54:01
   at Object.runWithContext (./client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2952:18)
2023-09-18 14:54:04
 [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'trim')
2023-09-18 14:54:04
   at desanitize (./client/.output/server/chunks/app/server.mjs:1243:52)  
2023-09-18 14:54:04
   at ./client/.output/server/chunks/app/server.mjs:1249:31  
2023-09-18 14:54:04
   at Array.reduce ()  
2023-09-18 14:54:04
   at parseCookieString (./client/.output/server/chunks/app/server.mjs:1246:139)  
2023-09-18 14:54:04
   at ./client/.output/server/chunks/app/server.mjs:1488:19  
2023-09-18 14:54:04
   at ./client/.output/server/chunks/app/server.mjs:124:70  
2023-09-18 14:54:04
   at fn (./client/.output/server/chunks/app/server.mjs:158:44)  
2023-09-18 14:54:04
   at Object.callAsync (./client/.output/server/node_modules/unctx/dist/index.mjs:68:55)  
2023-09-18 14:54:04
   at ./client/.output/server/chunks/app/server.mjs:160:56  
2023-09-18 14:54:04
   at Object.runWithContext (./client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2952:18)
2023-09-18 14:54:07
 [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'trim')
2023-09-18 14:54:07
   at desanitize (./client/.output/server/chunks/app/server.mjs:1243:52)  
2023-09-18 14:54:07
   at ./client/.output/server/chunks/app/server.mjs:1249:31  
2023-09-18 14:54:07
   at Array.reduce ()  
2023-09-18 14:54:07
   at parseCookieString (./client/.output/server/chunks/app/server.mjs:1246:139)  
2023-09-18 14:54:07
   at ./client/.output/server/chunks/app/server.mjs:1488:19  
2023-09-18 14:54:07
   at ./client/.output/server/chunks/app/server.mjs:124:70  
2023-09-18 14:54:07
   at fn (./client/.output/server/chunks/app/server.mjs:158:44)  
2023-09-18 14:54:07
   at Object.callAsync (./client/.output/server/node_modules/unctx/dist/index.mjs:68:55)  
2023-09-18 14:54:07
   at ./client/.output/server/chunks/app/server.mjs:160:56  
2023-09-18 14:54:07
   at Object.runWithContext (./client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2952:18)
2023-09-18 14:54:10
 [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'trim')
2023-09-18 14:54:10
   at desanitize (./client/.output/server/chunks/app/server.mjs:1243:52)  
2023-09-18 14:54:10
   at ./client/.output/server/chunks/app/server.mjs:1249:31  
2023-09-18 14:54:10
   at Array.reduce ()  
2023-09-18 14:54:10
   at parseCookieString (./client/.output/server/chunks/app/server.mjs:1246:139)  
2023-09-18 14:54:10
   at ./client/.output/server/chunks/app/server.mjs:1488:19  
2023-09-18 14:54:10
   at ./client/.output/server/chunks/app/server.mjs:124:70  
2023-09-18 14:54:10
   at fn (./client/.output/server/chunks/app/server.mjs:158:44)  
2023-09-18 14:54:10
   at Object.callAsync (./client/.output/server/node_modules/unctx/dist/index.mjs:68:55)  
2023-09-18 14:54:10
   at ./client/.output/server/chunks/app/server.mjs:160:56  
2023-09-18 14:54:10
   at Object.runWithContext (./client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2952:18)
2023-09-18 14:54:11
 [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'trim')
2023-09-18 14:54:11
   at desanitize (./client/.output/server/chunks/app/server.mjs:1243:52)  
2023-09-18 14:54:11
   at ./client/.output/server/chunks/app/server.mjs:1249:31  
2023-09-18 14:54:11
   at Array.reduce ()  
2023-09-18 14:54:11
   at parseCookieString (./client/.output/server/chunks/app/server.mjs:1246:139)  
2023-09-18 14:54:11
   at ./client/.output/server/chunks/app/server.mjs:1488:19  
2023-09-18 14:54:11
   at ./client/.output/server/chunks/app/server.mjs:124:70  
2023-09-18 14:54:11
   at fn (./client/.output/server/chunks/app/server.mjs:158:44)  
2023-09-18 14:54:11
   at Object.callAsync (./client/.output/server/node_modules/unctx/dist/index.mjs:68:55)  
2023-09-18 14:54:11
   at ./client/.output/server/chunks/app/server.mjs:160:56  
2023-09-18 14:54:11
   at Object.runWithContext (./client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2952:18)
```

**Comment by moisout** [comment]
Hi, can you try deleting the cookies for the page in your browser?

**Comment by Jogai** [comment]
Had not used chrome to try before so used that, but still no dice. Cleaned all storage of firefox (cookies, local storage etc.) but still wouldnt work. Tried with `mauriceo/viewtube:latest` today because I removed all containers yesterday, so even that should be a clean slate (containers are nice that way).

**Comment by moisout** [comment]
Does the error appear when you access it or directly after starting?

**Comment by Jogai** [comment]
The following log appears after just starting the containers, without accessing them:

```
2023-09-19 22:36:22
 [ViewTube] Info	9/19/2023, 10:36:22 PM Server listening on http://0.0.0.0:8066 - {}

2023-09-19 22:36:32
 [ViewTube] Error	9/19/2023, 10:36:32 PM [ExceptionsHandler] fetch failed - {"stack":["TypeError: fetch failed\n    at fetch (/home/app/node_modules/.pnpm/undici@5.23.0/node_modules/undici/index.js:109:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]}

2023-09-19 22:36:40
 [ViewTube] Error	9/19/2023, 10:36:40 PM [ExceptionsHandler] fetch failed - {"stack":["TypeError: fetch failed\n    at fetch (/home/app/node_modules/.pnpm/undici@5.23.0/node_modules/undici/index.js:109:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]}

**Comment by moisout** [comment]
Hmm, does your container have internet access?

**Comment by Jogai** [comment]
Yes, I can go to the shell of the container and install packages with pnpm. 

Output of `ls /home/app/client/.output/server/node_modules/@vue/runtime-core/dist/` : 
`runtime-core.cjs.js  runtime-core.cjs.prod.js`

**Comment by moisout** [comment]
Can you try the latest dev version and see if the trim() error still shows up?

Unfortunately i cannot reproduce it, so i can only guess what it could be😅

**Comment by Jogai** [comment]
Latest nightly is ok!

**Comment by moisout** [comment]
I'm glad!
If you encounter any other issues, feel free to open an issue.
