### ISSUE TITLE
[ExceptionsHandler] connect EADDRNOTAVAIL

### ISSUE THREAD

**Issue by nomonkeynodeal** [mauriceoegerli/viewtube-vue#2600]
### Describe the Bug

I really love ViewTube. It is such an upgrade over Invidious. My installation is mostly working, but I'm having an issue with certain specific channels.

I'm getting 500 errors and pages that just stop loading, often in the videos tab of a channel. The most recent one is /channel/UC9qJWqnmPhDLnZNllSQ8uQA/videos

This was happening on another channel yesterday. Today I tried that one and it worked.

Here are some log errors:

`[ViewTube] Error        1/27/2024, 4:32:16 PM [ExceptionsHandler] connect EADDRNOTAVAIL ::1:80 - Local (:::0) - {"stack":["Error: connect EADDRNOTAVAIL ::1:80 - Local (:::0)\n    at internalConnect (node:net:1100:16)\n    at defaultTriggerAsyncIdScope (node:internal/async_hooks:462:18)\n    at node:net:1306:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)"]}
[ViewTube] Error        1/27/2024, 4:33:58 PM [ExceptionsHandler] connect EADDRNOTAVAIL ::1:80 - Local (:::0) - {"stack":["Error: connect EADDRNOTAVAIL ::1:80 - Local (:::0)\n    at internalConnect (node:net:1100:16)\n    at defaultTriggerAsyncIdScope (node:internal/async_hooks:462:18)\n    at node:net:1306:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)"]}
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'length')
  at ./client/.output/server/chunks/app/_nuxt/_id_-c43Kejma.mjs:904:59  
  at renderComponentSubTree (./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:433:9)  
  at renderComponentVNode (./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:379:12)  
  at ssrRenderComponent (./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:86:10)  
  at ./client/.output/server/chunks/app/_nuxt/_id_-c43Kejma.mjs:1031:15  
  at renderComponentSubTree (./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:433:9)  
  at ./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:377:25  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async unrollBuffer$1 (./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:620:16)  
  at async unrollBuffer$1 (./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:625:16)
[ViewTube] Error        1/27/2024, 4:34:31 PM [ExceptionsHandler] connect EADDRNOTAVAIL ::1:80 - Local (:::0) - {"stack":["Error: connect EADDRNOTAVAIL ::1:80 - Local (:::0)\n    at internalConnect (node:net:1100:16)\n    at defaultTriggerAsyncIdScope (node:internal/async_hooks:462:18)\n    at node:net:1306:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)"]}
[ViewTube] Error        1/27/2024, 4:34:53 PM [ExceptionsHandler] connect EADDRNOTAVAIL ::1:80 - Local (:::0) - {"stack":["Error: connect EADDRNOTAVAIL ::1:80 - Local (:::0)\n    at internalConnect (node:net:1100:16)\n    at defaultTriggerAsyncIdScope (node:internal/async_hooks:462:18)\n    at node:net:1306:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)"]}`

### Device Info

Running in an unRAID docker in bridge mode. I tried custom mode with its own IP, but the docker wouldn't start.

**Comment by moisout** [comment]
Channels are currently unreliable due to changes from ViewTube. I will update once i am working on a fix.
