### ISSUE TITLE
Video playback error

### ISSUE THREAD

**Issue by curo1305** [mauriceoegerli/viewtube-vue#2834]
### Describe the Bug

Videos fails to play after a few seconds. Gives an error message "MEDIA_ERR_DECODE: NS_ERROR_DOM+MEDIA_METADATA_ERR (0x806e0006)".

### Steps to Reproduce the Bug

1. Play any video
2. wait a few seconds
3. Error is shown

### Screenshot/Screen recording

![viewtube_playback_error](https://github.com/ViewTube/viewtube/assets/76649382/ca6710d9-4b3f-4808-a388-24a5ab4dba7d)

### Device Info

- Device: Desktop PC
- OS: Windows 10
- Browser: Firefox
- Version: 127.0 (64-bit)

### Additional Context

- local self hosted solution
- the viewtube docker logs are showing an additional error

```
[ViewTube] 1      - 6/14/2024, 11:29:44 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'post') - {"stack":["TypeError: Cannot read properties of undefined (reading 'post')\n    at /home/app/server/dist/core/channels/yt-channel-info/app/YoutubeGrabberHelper.js:356:74\n    at Array.forEach (<anonymous>)\n    at YoutubeGrabberHelper.createCommunityPostArray (/home/app/server/dist/core/channels/yt-channel-info/app/YoutubeGrabberHelper.js:351:19)\n    at YoutubeGrabberHelper.parseCommunityPage (/home/app/server/dist/core/channels/yt-channel-info/app/YoutubeGrabberHelper.js:343:25)\n    at YoutubeGrabber.getChannelCommunityPosts (/home/app/server/dist/core/channels/yt-channel-info/app/YoutubeGrabber.js:401:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]}
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'length')
  at ./client/.output/server/chunks/build/_id_-RE7BqYv2.mjs:1561:59  
  at renderComponentSubTree (./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:430:9)  
  at ./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:374:25  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async unrollBuffer$1 (./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:617:16)  
  at async unrollBuffer$1 (./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:622:16)  
  at async unrollBuffer$1 (./client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:622:16)
```

**Comment by iwannet** [comment]
Could this be due to youtube testing server-side ads ?
