### ISSUE TITLE
Error trying to play video

### ISSUE THREAD

**Issue by blade10101** [mauriceoegerli/viewtube-vue#2884]
### Steps to Reproduce the Bug

1.
2.
3.

### Device Info

- Browser: [e.g. Firefox, Safari]
- Version: [e.g. 22]

### Additional Context

<!--  MEDIA_ERR_SRC_NOT_SUPPORTED: MEDIA_ELEMENT_ERROR: Media load rejected by URL safety check

[ViewTube] 1      - 6/27/2024, 3:37:42 PM   ERROR [ExceptionsHandler] Request failed with status code 404 - {"stack":["AxiosError: Request failed with status code 404\n    at settle (/home/app/node_modules/.pnpm/axios@1.7.2/node_modules/axios/dist/node/axios.cjs:1983:12)\n    at Unzip.handleStreamEnd (/home/app/node_modules/.pnpm/axios@1.7.2/node_modules/axios/dist/node/axios.cjs:3085:11)\n    at Unzip.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/home/app/node_modules/.pnpm/axios@1.7.2/node_modules/axios/dist/node/axios.cjs:4224:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async YoutubeGrabberHelper.makeChannelRequest (/home/app/server/dist/core/channels/yt-channel-info/app/YoutubeGrabberHelper.js:31:30)\n    at async YoutubeGrabberHelper.performChannelRequest (/home/app/server/dist/core/channels/yt-channel-info/app/YoutubeGrabberHelper.js:687:37)\n    at async YoutubeGrabberHelper.performCUrlRequest (/home/app/server/dist/core/channels/yt-channel-info/app/YoutubeGrabberHelper.js:717:16)\n    at async /home/app/server/dist/core/channels/yt-channel-info/app/YoutubeGrabberHelper.js:700:28\n    at async /home/app/server/dist/core/channels/yt-channel-info/app/YoutubeGrabberHelper.js:699:24\n    at async /home/app/server/dist/core/channels/yt-channel-info/app/YoutubeGrabberHelper.js:698:20\n    at async YoutubeGrabberHelper.performChannelPageRequestWithFallbacks (/home/app/server/dist/core/channels/yt-channel-info/app/YoutubeGrabberHelper.js:697:16)\n    at async YoutubeChannelFetcher.getChannelList (/home/app/server/dist/core/channels/yt-channel-info/app/fetchers/YoutubeChannelFetcher.js:34:37)"]}>

**Comment by moisout** [comment]
You need to provide more information, otherwise this issue is not helpful
