### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by wes1993** [mauriceoegerli/viewtube-vue#2988]
### Describe the Bug
When search somethig the error "Cannot read properties of undefined (reading 'match')" appear.
I have see that chosing in filter some value make the search working again

### Steps to Reproduce the Bug
1. Search Something
2. Click enter

### Expected Behaviour

Should search using some predefined filter, example all

### Screenshot/Screen recording

![image](https://github.com/user-attachments/assets/51689342-42e9-438c-9f3b-4393dd2e4bdb)

### Device Info

- Device: PC
- OS: Windows 11
- Browser: Chrome
- Version: 129.0.6668.90

**Comment by gareins** [comment]
This generates errors in logs:

```
viewtube-main       | [ViewTube] 1      - 10/18/2024, 11:23:06 AM   ERROR [ExceptionsHandler] Package subpath './dist/protos/generated/misc/params' is not defined by "exports" in /home/app/server/node_modules/youtubei.js/package.json - {"stack":["Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/protos/generated/misc/params' is not defined by \"exports\" in /home/app/server/node_modules/youtubei.js/package.json\n    at exportsNotFound (node:internal/modules/esm/resolve:304:10)\n    at packageExportsResolve (node:internal/modules/esm/resolve:651:9)\n    at resolveExports (node:internal/modules/cjs/loader:634:36)\n    at Module._findPath (node:internal/modules/cjs/loader:724:31)\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)\n    at Module._load (node:internal/modules/cjs/loader:1051:27)\n    at Module.require (node:internal/modules/cjs/loader:1311:19)\n    at require (node:internal/modules/helpers:179:18)\n    at /home/app/server/dist/core/search/search.service.js:80:229\n    at async SearchService.getSearch (/home/app/server/dist/core/search/search.service.js:80:156)"]}
viewtube-main       | [ViewTube] 1      - 10/18/2024, 11:23:06 AM   ERROR [ExceptionsHandler] Package subpath './dist/protos/generated/misc/params' is not defined by "exports" in /home/app/server/node_modules/youtubei.js/package.json - {"stack":["Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/protos/generated/misc/params' is not defined by \"exports\" in /home/app/server/node_modules/youtubei.js/package.json\n    at exportsNotFound (node:internal/modules/esm/resolve:304:10)\n    at packageExportsResolve (node:internal/modules/esm/resolve:651:9)\n    at resolveExports (node:internal/modules/cjs/loader:634:36)\n    at Module._findPath (node:internal/modules/cjs/loader:724:31)\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)\n    at Module._load (node:internal/modules/cjs/loader:1051:27)\n    at Module.require (node:internal/modules/cjs/loader:1311:19)\n    at require (node:internal/modules/helpers:179:18)\n    at /home/app/server/dist/core/search/search.service.js:80:229\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]}
```

**Comment by gareins** [comment]
Seems like there was some proto generation changed in 10.0.4 -> 10.0.5 of youtubei.js dependency: https://github.com/LuanRT/YouTube.js/commit/94bc59604852dc624eae2aa07f0e8fe2f5f75a53

Then two weeks ago in 8979b7a7acbc5b7b2f0d1da6a1e4cb10e850b09c it looks to me like @moisout somehow used code from those generated files, but the code does not seem to be exported by the dependency. I have no idea how this crazy ts/js build world works, but I'll dig on to see if I can get to the root problem here.

Also later in 44606cfd5daf3d6f64c1c7899b1d1d58f8d47c61 some fixes were made to import stuff at runtime.

**Comment by wes1993** [comment]
@gareins Thanks a lot for your reply!!!

**Comment by gareins** [comment]
I have now managed to reproduce this. I had removed the code changes in last two commits and comments on videos now load and I get this same match error. Just to paste the whole error from the instance: 

```
viewtube-main       | [ViewTube] 1      - 10/21/2024, 11:18:53 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'match') - {"stack":["TypeError: Cannot read properties of undefined (reading 'match')\n    at parseAccessibilityDuration (/home/app/server/dist/mapper/utils/accessibility-duration.js:12:53)\n    at extractSearchShort (/home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:104:76)\n    at /home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:93:41\n    at Proxy.map (<anonymous>)\n    at extractSearchShortsShelf (/home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:93:29)\n    at /home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:28:24\n    at Proxy.map (<anonymous>)\n    at extractSearchResults (/home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:19:27)\n    at toVTSearchResultDto (/home/app/server/dist/mapper/converter/search/vt-search-result.converter.js:14:69)\n    at SearchService.getSearch (/home/app/server/dist/core/search/search.service.js:60:65)"]}
viewtube-main       | [ViewTube] 1      - 10/21/2024, 11:18:54 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'match') - {"stack":["TypeError: Cannot read properties of undefined (reading 'match')\n    at parseAccessibilityDuration (/home/app/server/dist/mapper/utils/accessibility-duration.js:12:53)\n    at extractSearchShort (/home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:104:76)\n    at /home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:93:41\n    at Proxy.map (<anonymous>)\n    at extractSearchShortsShelf (/home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:93:29)\n    at /home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:28:24\n    at Proxy.map (<anonymous>)\n    at extractSearchResults (/home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:19:27)\n    at toVTSearchResultDto (/home/app/server/dist/mapper/converter/search/vt-search-result.converter.js:14:69)\n    at SearchService.getSearch (/home/app/server/dist/core/search/search.service.js:60:65)"]}
```

Will look into it now.

**Comment by LordS4me** [comment]
Any news on this ?

**Comment by engynious** [comment]
Also piggy-backing this issue.

**Comment by Cynopolis** [comment]
Same issue here
