### ISSUE TITLE
external redis with password not working

### ISSUE THREAD

**Issue by mamema** [mauriceoegerli/viewtube-vue#916]
### Describe the Bug
password authentication not working (using latest docker image

### Steps to Reproduce the Bug
create env vars:

VIEWTUBE_REDIS_HOST
VIEWTUBE_REDIS_PASSWORD
VIEWTUBE_REDIS_PORT

got:

}
node:events:371
      throw er; // Unhandled 'error' event
      ^
ReplyError: Ready check failed: NOAUTH Authentication required.
    at parseError (/home/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/app/node_modules/redis-parser/lib/parser.js:302:14)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_info_cmd (/home/app/node_modules/redis/index.js:432:14)
    at /home/app/node_modules/redis/index.js:471:14
    at Object.callbackOrEmit [as callback_or_emit] (/home/app/node_modules/redis/lib/utils.js:89:9)
    at /home/app/node_modules/redis/lib/individualCommands.js:157:15
    at Object.callbackOrEmit [as callback_or_emit] (/home/app/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/home/app/node_modules/redis/index.js:642:11)
    at JavascriptRedisParser.returnError (/home/app/node_modules/redis/index.js:142:18)
    at JavascriptRedisParser.execute (/home/app/node_modules/redis-parser/lib/parser.js:542:14)
    at Socket.<anonymous> (/home/app/node_modules/redis/index.js:219:27)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  command: 'INFO',
  code: 'NOAUTH'
}

### Expected Behaviour
as this redis server is working with password with other services, the viewtube container is the culprit 

- Device: osx chrome Browser
- OS: docker is running on debian 10 - latest release updates
- Browser:chrome
- Version: 93.0

**Comment by moisout** [comment]
Hi, i forgot to add the password env variable to the cache service. Should be fixed with #918. I'll update here once it's released on viewtube dev.

**Comment by moisout** [comment]
the mauriceo/viewtube:dev image is now updated, can you try it again?

**Comment by mamema** [comment]
yes, sure. Tried again. Problem solved!
